#!/bin/bash

# Start Auto-Logger for Claude Code Conversations
# This script monitors Claude Code activity and logs conversations to .specstory/history

PROJECT_PATH="${1:-$(pwd)}"

echo "Starting Claude Code Auto-Logger..."
echo "Project path: $PROJECT_PATH"
echo "Logs will be saved to: $PROJECT_PATH/.specstory/history/"

# Ensure the directory exists
mkdir -p "$PROJECT_PATH/.specstory/history"

# Create a monitoring script
cat > /tmp/claude-monitor.js << 'EOF'
const fs = require('fs');
const path = require('path');
const readline = require('readline');

class ClaudeLogger {
  constructor(projectPath) {
    this.projectPath = projectPath;
    this.historyPath = path.join(projectPath, '.specstory', 'history');
    this.currentSession = null;
    this.sessionFile = null;
    this.messageBuffer = [];
    
    // Ensure directory exists
    if (!fs.existsSync(this.historyPath)) {
      fs.mkdirSync(this.historyPath, { recursive: true });
    }
  }

  generateSessionFilename() {
    const now = new Date();
    const date = now.toISOString().split('T')[0];
    const time = now.toTimeString().split(' ')[0].replace(/:/g, '-');
    return `${date}_${time}_claude-code-session.md`;
  }

  startSession() {
    const filename = this.generateSessionFilename();
    this.sessionFile = path.join(this.historyPath, filename);
    this.currentSession = {
      startTime: new Date().toISOString(),
      messages: []
    };
    
    const header = `<!-- Generated by Claude Code Auto-Logger -->

# Claude Code Session (${new Date().toISOString()})

**Project:** ${this.projectPath}  
**Started:** ${this.currentSession.startTime}  

---

`;
    
    fs.writeFileSync(this.sessionFile, header);
    console.error(`[Logger] Started new session: ${filename}`);
  }

  logMessage(role, content) {
    if (!this.currentSession) {
      this.startSession();
    }

    const timestamp = new Date().toISOString();
    const message = {
      role,
      content,
      timestamp
    };

    this.currentSession.messages.push(message);
    
    // Append to file
    const formatted = role === 'user' 
      ? `## User\n\n*${timestamp}*\n\n${content}\n\n---\n\n`
      : `## Assistant\n\n*${timestamp}*\n\n${content}\n\n---\n\n`;
    
    fs.appendFileSync(this.sessionFile, formatted);
    console.error(`[Logger] Logged ${role} message`);
  }

  endSession() {
    if (this.currentSession && this.sessionFile) {
      const endTime = new Date().toISOString();
      const footer = `\n**Session Ended:** ${endTime}  \n**Total Messages:** ${this.currentSession.messages.length}\n`;
      fs.appendFileSync(this.sessionFile, footer);
      console.error('[Logger] Session ended');
    }
    this.currentSession = null;
    this.sessionFile = null;
  }
}

// Initialize logger
const projectPath = process.argv[2] || process.cwd();
const logger = new ClaudeLogger(projectPath);

// Create readline interface for stdin
const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
  terminal: false
});

let inputBuffer = '';
let isUserInput = true;

// Process input line by line
rl.on('line', (line) => {
  // Simple heuristic: alternate between user and assistant
  // In practice, you'd parse the Claude Code protocol
  
  if (line.trim() === '---' || line.trim() === '') {
    if (inputBuffer.trim()) {
      logger.logMessage(isUserInput ? 'user' : 'assistant', inputBuffer.trim());
      inputBuffer = '';
      isUserInput = !isUserInput;
    }
  } else {
    inputBuffer += line + '\n';
  }
  
  // Pass through
  console.log(line);
});

// Handle shutdown
process.on('SIGINT', () => {
  logger.endSession();
  process.exit(0);
});

process.on('SIGTERM', () => {
  logger.endSession();
  process.exit(0);
});

console.error('[Logger] Claude Code Auto-Logger started');
console.error(`[Logger] Monitoring project: ${projectPath}`);
EOF

# Run the monitor
node /tmp/claude-monitor.js "$PROJECT_PATH"